sudo: required
dist: trusty
language: node_js
install:
  - sudo apt-get install python-setuptools postgresql-server-dev-9.6 postgresql-contrib
  - sudo easy_install pgxnclient
  - sudo pgxn install pgtap
  - sudo PERL_MM_USE_DEFAULT=1 cpan TAP::Parser::SourceHandler::pgTAP
addons:
  postgresql: "9.6"
services:
    - postgresql
before_script:
  - psql -U postgres -c "CREATE DATABASE terasologykeys;"
  - psql -U postgres -d terasologykeys -c "CREATE EXTENSION \"uuid-ossp\";"
  - psql -U postgres -d terasologykeys -c "CREATE EXTENSION pgtap;"
script:
  - cat sql/*.sql | psql -d terasologykeys
  - pg_prove -U postgres -d terasologykeys sql/test/*.sql
