version: '2'
services:
  webapp:
    build: ./webapp
    ports:
    - 80:8080
    environment:
    - HTTP_MODE=preserveHttp
    - HTTP_PORT=8080
    - DB_HOST=database
    - DB_PORT=5432
    - DB_NAME=terasologykeys
    - DB_USER=terasologykeys_app
    - DB_PASSWORD=${DB_PASSWORD}
    - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
  database:
    build: ./sql
    environment:
    - APP_USER_NAME=terasologykeys_app
    - APP_USER_PASSWORD=${DB_PASSWORD}
    - APP_HOSTNAME=webapp
    - SMTP_SERVER=mailer
    - SMTP_PORT=25
    - SMTP_USER=noreply@localhost
    - SMTP_PASS=${MAIL_PASSWORD}
    - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
  mailer:
    image: "catatnight/postfix:latest"
    environment:
    - smtp_user=noreply@localhost:${MAIL_PASSWORD}
    - maildomain=localhost
